# Generated by Django 6.0.1 on 2026-02-20 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '__first__'),
        ('inquiries', '0001_initial'),
        ('products', '0003_product_discount_price_product_is_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiryitem',
            name='clothing_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clothing.clothingproduct'),
        ),
        migrations.AlterField(
            model_name='inquiryitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
