# Generated by Django 6.0.1 on 2026-02-20 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, help_text='SEO Title', max_length=255)),
                ('meta_description', models.TextField(blank=True, help_text='SEO Description')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='clothing/categories/')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Clothing Categories',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hex_code', models.CharField(blank=True, help_text='e.g. #FFFFFF', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ClothingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, help_text='SEO Title', max_length=255)),
                ('meta_description', models.TextField(blank=True, help_text='SEO Description')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', models.ImageField(upload_to='clothing/products/')),
                ('hover_image', models.ImageField(blank=True, null=True, upload_to='clothing/products/')),
                ('short_description', models.TextField(help_text='Shown in listing')),
                ('full_description', models.TextField()),
                ('material', models.CharField(blank=True, max_length=255)),
                ('features', models.TextField(blank=True, help_text='Bullet points')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='clothing.clothingcategory')),
                ('colors', models.ManyToManyField(blank=True, to='clothing.color')),
                ('sizes', models.ManyToManyField(blank=True, to='clothing.size')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
