# Generated by Django 6.0.1 on 2026-02-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingproduct',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='clothing/products/'),
        ),
        migrations.AddField(
            model_name='clothingproduct',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='clothing/products/'),
        ),
        migrations.AddField(
            model_name='clothingproduct',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='clothing/products/'),
        ),
        migrations.AddField(
            model_name='clothingproduct',
            name='image_6',
            field=models.ImageField(blank=True, null=True, upload_to='clothing/products/'),
        ),
        migrations.AlterField(
            model_name='clothingproduct',
            name='hover_image',
            field=models.ImageField(blank=True, help_text='Hover Image / 2nd View', null=True, upload_to='clothing/products/'),
        ),
        migrations.AlterField(
            model_name='clothingproduct',
            name='image',
            field=models.ImageField(help_text='Main Image', upload_to='clothing/products/'),
        ),
    ]
