# Generated by Django 6.0.1 on 2026-02-27 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0002_clothingproduct_image_3_clothingproduct_image_4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingproduct',
            name='image',
            field=models.ImageField(help_text='Main Image (Recommended: 3:4 ratio, e.g., 800x1066px)', upload_to='clothing/products/'),
        ),
    ]
