# Generated by Django 6.0.1 on 2026-02-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qr_code',
            field=models.ImageField(blank=True, help_text='Upload QR code image', null=True, upload_to='products/qrcodes/'),
        ),
    ]
